name: Build Node.js Package

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Grant execute permission to edit_packageJSON.sh
      run: chmod +x ./scripts/edit_packageJSON.sh
    
    - name: Edit package.json for gaudi-iot-device
      run: ./scripts/edit_packageJSON.sh
      env: 
        VERSION: 0.0.1-test
        SDK_VERSION: '6.0.0'
    
    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
    
    - name: install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}