name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
       
    - name: Grant execute permission to edit_packageJSON.sh
      run: chmod +x ./tools/edit_packageJSON.sh
  
    - name: Edit package.json for gaudi-iot-device
      run: ./tools/edit_packageJSON.sh
      env: 
        VERSION: ${{ github.event.release.tag_name }}
        SDK_VERSION: '6.0.0'
    
    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@project-gaudi'
        always-auth: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        